export const EnglishCategoryToPersian = {
    "interesting_places": "مکان های دیدنی",
    "religion": "مذهبی",
    "cultural": "فرهنگی",
    "historic": "تاریخی",
    "industrial_facilities": "امکانات صنعتی",
    "natural": "طبیعت",
    "other": "سایر",
    "tourist_facilities": "امکانات توریستی",
    "transport": "وسایل نقلیه",
    "shops": "فروشگاه",
    "foods": "غذا خوری",
    "banks": "بانک",
    "car_rental": "اجاره ماشین",
    "car_sharing": "اجاره ماشین",
    "car_wash": "کارواش",
    "bicycle_rental": "اجاره دوچرخه",
    "boat_sharing": "لنگرگاه",
    "fuel": "پمپ سوخت",
    "restaurants": "رستوران",
    "cafes": "کافی شاپ",
    "fast_food": "فست فود",
    "food_courts": "فود کورت",
    "picnic_sites": "محوطه پیکنیک",
    "sport": "ورزشی",
    "amusements": "سرگرمی",
    "accomodations": "اقامتگاه",
}