export const EXPAND='EXPAND'
export const CHECK='CHECK'
export const SELECT='SELECT'
export const SEARCHAREA='SEARCHAREA'
export const CURRENT='CURRENT'
export const ICONHANDLER='ICONHANDLER'
export const ONSERACH='ONSERACH'
export const MODALDETAILSHOW='MODALDETAILSHOW'
